# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Rarefy Matrix
NULL

rarefy_matrix <- function(mat, N) {
    .Call(`_EasyMultiOmics_rarefy_matrix`, mat, N)
}

#' @title Schur Product
NULL

schur <- function(a, b) {
    .Call(`_EasyMultiOmics_schur`, a, b)
}

