# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

schur <- function(a, b) {
    .Call(`_EasyMultiOmics_schur`, a, b)
}

FEAST_core <- function(sources, sinks, em_iterations = 1000L) {
    .Call(`_EasyMultiOmics_FEAST_core`, sources, sinks, em_iterations)
}

